// Generated by Wrangler on Sun Mar 31 2024 11:37:11 GMT+0500 (Pakistan Standard Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "production_value";
	JWT_SECRET: "test";
	DB: D1Database;
}
