// Generated by Wrangler on Fri Apr 05 2024 03:37:29 GMT+0500 (Pakistan Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: "test";
	GOOGLE_CLIENT_SECRET: "test";
	STMP_EMAIL: "test";
	STMP_PASSWORD: "test";
	JWT_SECRET: "test";
	SEND_GRID_API_KEY: "test";
	MAPBOX_ACCESS_TOKEN: "test";
	OSM_URI: "test";
	WEATHER_URL: "test";
	WEATHER_WEEK_URL: "test";
	OPENWEATHER_KEY: "test";
	DB: D1Database;
}
