#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "🔍 Running pre-push hook"

# Running tests
echo "🔄 Running tests..."
# yarn test

if [ $? -eq 0 ]; then
  echo -e "${GREEN}✅ Tests passed${NC}"
else
  echo -e "${RED}❌ Tests failed${NC}"
  exit 1
fi

# Running yarn lint
echo "🔄 Running yarn lint..."
yarn lint

if [ $? -eq 0 ]; then
  echo -e "${GREEN}✅ Yarn lint passed${NC}"
else
  echo -e "${RED}❌ Yarn lint failed${NC}"
  exit 1
fi