name: Lint and Build

on:
  pull_request:
    paths-ignore:
      - '**.md' # Don't run on Markdown file changes

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or whatever version you prefer

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint:all

  build:
    needs: lint # Only runs if lint job is successful
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Comment PR if build fails
      if: failure()
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'The build failed! Please check the logs and fix the issues.'
          });



